# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install wget
  - wget https://bintray.com/quantlib/releases/download_file?file_path=QuantLib-1.16.tar.gz
  - tar -czvf QuantLib-1.16.tar.gz
  - cd QuantLib-1.16
  - ./configure --with-boost-include=/home/foo/include --with-boost-lib=/home/foo/lib
  - make
  - sudo make install

after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
